import type { Metadata } from "next";
import "./globals.css";
import { ConvexAuthNextjsServerProvider } from "@convex-dev/auth/nextjs/server";
import { ConvexClientProvider } from "@/components/providers/convex-client-provider";
import { Modal } from "@/components/Modal";
import { Toaster } from "@/components/ui/toaster";
import JotaiProvider from "@/components/providers/jotai-provider";
import { Noto_Sans } from "next/font/google";
import { NuqsAdapter } from "nuqs/adapters/next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const whitney = Noto_Sans({
    subsets: ["latin"],
    weight: ["400", "700"],
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ConvexAuthNextjsServerProvider>
            <html lang="vi">
                <body className={`antialiased ${whitney.className}`}>
                    <ConvexClientProvider>
                        <NuqsAdapter>
                            <JotaiProvider>
                                <Toaster />
                                <Modal />
                                {children}
                            </JotaiProvider>
                        </NuqsAdapter>
                    </ConvexClientProvider>
                </body>
            </html>
        </ConvexAuthNextjsServerProvider>
    );
}
